spring:
  application:
    name: map-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update      # 필요에 따라 create, validate 변경
    open-in-view: false
    generate-ddl: true

  # 로컬에서는 Config Server 사용 X
  config:
    import: ""          # ← 기본 application.yml의 configserver import를 빈 값으로 덮어쓰기
  cloud:
    config:
      enabled: false
      discovery:
        enabled: false
eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: localhost
#    non-secure-port: 3334
#    health-check-url-path: /actuator/health

  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:3150/eureka/

springdoc:
  version: '1.0.0'
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs.html

server:
  port: 8080
