#spring:
#  application:
#    name: map-service
#
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    # DB_URL = ${DB_HOST}:${DB_PORT}/${DB_NAME} 라는 전제
#    url: jdbc:postgresql://${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#
#  jpa:
#    open-in-view: false
#    generate-ddl: true
#    hibernate:
#      # .env의 DB_DDL_AUTO로 제어 (없으면 update)
#      ddl-auto: ${DB_DDL_AUTO:update}
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#
#  # 로컬에서는 Config Server 사용 X
#  config:
#    import: "optional:configserver:"
#  cloud:
#    config:
#      discovery:
#        enabled: false
#
#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
#    non-secure-port: 3334
#    health-check-url-path: /actuator/health
#
#  client:
#    register-with-eureka: false
#    fetch-registry: false
#    service-url:
#      defaultZone: http://localhost:3150/eureka/
#
#springdoc:
#  version: "1.0.0"
#  api-docs:
#    path: /v3/api-docs
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  swagger-ui:
#    operations-sorter: alpha
#    tags-sorter: alpha
#    path: /api-docs.html
#
#graphhopper:
#  base-url: ${GRAPHHOPPER_BASE_URL:http://localhost:8989}
#
#server:
#  port: 8080
