server:
  application_connectors:
    - type: http
      port: 8989
  admin_connectors:
    - type: http
      port: 8990

graphhopper:
  graph.location: /graphhopper/graph-cache
  datareader.file: /graphhopper/data/gangnam.osm
  datareader.dataaccess: RAM_STORE

  import.osm.ignored_highways: ""

  encoded_values: road_class,road_environment,surface,track_type,foot,access

  profiles:
    - name: foot
      vehicle: foot
      weighting: fastest
    - name: wheelchair
      vehicle: foot
      weighting: fastest

  routing:
    CH:
      enabled: true
    LM:
      enabled: false
